from typing import Optional, Protocol, Union

from src.application.dto import UserDto
from src.core.enums import UserRole


class UserDAO(Protocol):
    async def create(self, user: UserDto) -> UserDto: ...

    async def get_by_telegram_id(self, telegram_id: int) -> Optional[UserDto]: ...

    async def get_by_telegram_ids(self, telegram_ids: list[int]) -> list[UserDto]: ...

    async def get_by_partial_name(self, query: str) -> list[UserDto]: ...

    async def get_all(self, limit: int = 100, offset: int = 0) -> list[UserDto]: ...

    async def exists(self, telegram_id: int) -> bool: ...

    async def update(self, user: UserDto) -> Optional[UserDto]: ...

    async def delete(self, telegram_id: int) -> bool: ...

    async def count(self) -> int: ...

    async def filter_by_role(self, role: Union[UserRole, list[UserRole]]) -> list[UserDto]: ...

    async def set_bot_blocked_status(self, telegram_id: int, is_bot_blocked: bool) -> None: ...
